### PR TITLE
[Easy] Add Error Context to Smart Contract Bindings Generation

### LINKED ISSUE #106: Better Errors For `ethcontract::contract` Macro
It can be very difficult to debug issues where the contract JSON cannot be found, improve errors when locating the JSON file fails.

### PR DESCRIPTION
**Pull request by nlordell**
Closes #106

### CODE REVIEW

File: generate/src/contract/deployment.rs [hunk 1]
```diff
@@ -1,6 +1,6 @@
 use crate::contract::{methods, Context};
 use crate::util;
-use anyhow::Result;
+use anyhow::{Context as _, Result};
```
Comment (bh2smith) [inline generate/src/contract/deployment.rs:3]: What is the underscore being used for? I don't see it mentioned again later in the "Context"!

Comment (nlordell) [reply generate/src/contract/deployment.rs:3]: To use trait methods in Rust, the trait must be imported into the local scope. If you want to use the trait methods only but not actually use the trait anywhere else, you can import it `as _` so that you can call methods defined by the trait without worrying about name collisions. Here we have a struct called `Context` as well so using this anonymous import avoids any compiler errors from from `Context` already being in use.

Comment (nlordell) [reply generate/src/contract/deployment.rs:3]: The `Context` trait is needed for the `context` and `with_context` methods on the `anyhow::Result` type.

**Comment by nlordell** [comment]
Re-opened to give Travis a nudge.

**Review by fleupold — APPROVED** [review]
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia1.giphy.com%2Fmedia%2FghCeBSsrXl3igHacZc%2Fgiphy.gif&token=improve" data-gitmeme-token="improve"></a>
